# Default values for couchbase-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override default naming of chart resources
nameOverride: ""

# couchbaseCluster config
couchbaseCluster:
  # create flag to deploy couchbase cluster
  create: true
  # name of the cluster. defaults to name of chart release
  name: ""
  # username of the cluster admin.
  username: "Administrator"
  # password of the cluster admin.
  password: "password"
  # authSecretOverride is name of secret to use instead of using
  # the default secret with username and password specified above
  authSecretOverride: ""
  # BaseImage is the base couchbase image name that will be used to launch
  # couchbase clusters. This is useful for private registries, etc.
  baseImage: "couchbase/server"
  # Version is the expected version of the couchbase cluster
  version: "enterprise-5.5.1"
  # Option to expose admin console
  exposeAdminConsole: true
  # Option to expose admin console
  adminConsoleServices:
    - data
  # Specific services to use when exposing ui
  exposedFeatures:
    - xdcr
  # Defines how the admin console service is exposed.
  # Allowed values are NodePort and LoadBalancer.
  # If this field is LoadBalancer then you must also define a spec.dns.domain.
  adminConsoleServiceType: NodePort
  # Defines how the per Couchbase node ports are exposed.
  # Allowed values are NodePort and LoadBalancer.
  # If this field is LoadBalancer then you must also define a spec.dns.domain.
  exposedFeatureServiceType: NodePort
  # The retention period that log volumes are kept for after their associated pods have been deleted.
  logRetentionTime: 604800s
  # The maximum number of log volumes that can be kept after their associated pods have been deleted.
  logRetentionCount: 20
  # Dynamic DNS configuration to use for exposed features
  dns:
    domain:
  # Indicates which underlying cloud platform the Kubernetes cluster is running.
  # The Value must be one of aws, gce or azure
  platform:
  # Cluster wide settings for nodes and services
  cluster:
    # The amount of memory that should be allocated to the data service
    dataServiceMemoryQuota: 256
    # The amount of memory that should be allocated to the index service
    indexServiceMemoryQuota: 256
    # The amount of memory that should be allocated to the search service
    searchServiceMemoryQuota: 256
    # The amount of memory that should be allocated to the eventing service
    eventingServiceMemoryQuota: 256
    # The amount of memory that should be allocated to the analytics service
    analyticsServiceMemoryQuota: 1024
    # The index storage mode to use for secondary indexing
    indexStorageSetting: memory_optimized
    # Timeout that expires to trigger the auto failover.
    autoFailoverTimeout: 120
    # The number of failover events we can tolerate
    autoFailoverMaxCount: 3
    # Whether to auto failover if disk issues are detected
    autoFailoverOnDataDiskIssues: true
    # How long to wait for transient errors before failing over a faulty disk
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    # Whether to enable failing over a server group
    autoFailoverServerGroup: false

  # cluster buckets
  buckets:
    # The bucket name
    default:
      # The type of bucket to use
      type: couchbase
      # The amount of memory that should be allocated to the bucket
      memoryQuota: 128
      # The number of bucket replicates
      replicas: 1
      # The priority when compared to other buckets
      ioPriority: high
      # The bucket eviction policy which determines behavior during expire and high mem usage
      evictionPolicy: fullEviction
      # The bucket's conflict resolution mechanism; which is to be used if a conflict occurs during Cross Data-Center Replication (XDCR). Sequence-based and timestamp-based mechanisms are supported.
      conflictResolution: seqno
      # The enable flush option denotes wether the data in the bucket can be flushed
      enableFlush: true
      # Enable Index replica specifies whether or not to enable view index replicas for this bucket.
      enableIndexReplica: false
  servers:
    # Name for the server configuration. It must be unique.
    all_services:
      # Size of the couchbase cluster.
      size: 3
      # The services to run on nodes
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups: []
      # Pod defines the policy to create pod for the couchbase pod.
      pod: {}
  # couchbase cluster TLS configuration. Provide cluster secrets here
  # or set couchbaseTLS.create = true to auto-generate certs.
  tls: {}
  # Security Context for all pods
  securityContext: {}
  # VolumeClaimTemplates define the desired characteristics of a volume
  # that can be requested and claimed by a pod.
  volumeClaimTemplates: []

# couchbaseTLS uses certs to generate secrets used by the operator and couchbase cluster.
couchbaseTLS:
  # create TLS secrets and apply to couchbase server
  create: false
  # Expiry time of CA in days
  expiration: 365
  # clusterSecret is the secret containing TLS certs used by each couchbase member pod
  clusterSecret:
    name: ""
    # PEM format certificate for couchbase member Pods (auto-generated)
    # override via --set-file
    caCert: ""
  # OperatorSecret is the secret containing TLS certs used by operator
  operatorSecret:
    name: ""
    # PEM format certificate for operator (auto-generated)
    # override via --set-file
    tlsCert: ""
    # PEM format private key for operator (auto-generated)
    # override via --set-file
    tlsKey: ""
