apiVersion: v2
name: couchbase-operator
description: A Helm chart to deploy the Couchbase Autonomous Operator for easily deploying, managing, and maintaining Couchbase Clusters. Couchbase Server is a NoSQL document database with a distributed architecture for performance, scalability, and availability. It enables developers to build applications easier and faster by leveraging the power of SQL with the flexibility of JSON.
version: 2.30.3
appVersion: 2.3.0
type: application
keywords:
- couchbase
- operator
- database
- nosql
- cluster
- replication
home: https://couchbase.com
icon: https://couchbase-partners.github.io/helm-charts/assets/img/CB_Logomark_220.png
sources:
- https://docs.couchbase.com/operator/current/helm-setup-guide.html
maintainers:
- name: Couchbase Cloud Native Team
  email: kubernetes@couchbase.com
- name: Tommie McAfee
  email: tommie@couchbase.com
