{{- if .Values.install.syncGateway }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "couchbase-cluster.sg.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "couchbase-cluster.sg.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "couchbase-cluster.sg.name" . }}
    spec:
      containers:
      - name: sync-gateway
        image: "{{ .Values.syncGateway.image.repository }}:{{ .Values.syncGateway.image.tag }}"
        imagePullPolicy: {{ .Values.syncGateway.imagePullPolicy }}
        volumeMounts:
        - mountPath: /etc/sync_gateway
          name: config
          readOnly: true
        env:
        - name: GOMAXPROCS
          value: "1"
      volumes:
      - name: config
        secret:
          secretName: {{ template "couchbase-cluster.sg.secret" . }}
{{ if .Values.syncGateway.dns.service }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - {{ (lookup "v1" "Service" .Release.Namespace .Values.syncGateway.dns.service).spec.clusterIP }}
        searches:
{{- range  $name := .Values.syncGateway.dns.searches }}
        - {{ $name }}
{{- end -}}
{{- end -}}
{{- if (eq .Values.syncGateway.exposeServiceType "ClusterIP") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
  name: {{ include "couchbase-cluster.sg.name" . }}
spec:
  ports:
  - port: 4984
    protocol: TCP
    targetPort: 4984
  selector:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
  type: ClusterIP
{{- else if (eq .Values.syncGateway.exposeServiceType "NodePort") }}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
  name: {{ include "couchbase-cluster.sg.name" . }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4984
    protocol: TCP
    targetPort: 4984
  selector:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
  sessionAffinity: None
  type: NodePort
{{- else if (eq .Values.syncGateway.exposeServiceType "LoadBalancer") }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
{{- if .Values.cluster.networking.dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "couchbase-cluster.sg.externalname" . }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
  name: {{ include "couchbase-cluster.sg.name" . }}
spec:
  externalTrafficPolicy: Local
  ports:
  - name: sync-gateway-admin
    port: 4984
    protocol: TCP
    targetPort: 4984
  selector:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
  sessionAffinity: None
  type: LoadBalancer
{{- end -}}
{{- end -}}
