{{- if .Values.install.admissionController }}
{{ $tls := fromYaml ( include "admission-controller.gen-certs" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "admission-controller.secret.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
type: Opaque
data:
  tls-cert-file: {{ $tls.clientCert }}
  tls-private-key-file: {{ $tls.clientKey }}

{{- if (not .Values.admissionController.disableValidatingWebhook) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "admission-controller.fullname" . }}
webhooks:
- name: {{ include "admission-controller.service.fullname" . }}
  admissionReviewVersions:
  - v1
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ template "admission-controller.service.name" . }}
      path: "/couchbaseclusters/validate"
    caBundle: {{ $tls.caCert }}
{{- end -}}

{{- if (not .Values.admissionController.disableMutatingWebhook) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
webhooks:
- name: {{ include "admission-controller.service.fullname" . }}
  admissionReviewVersions:
  - v1
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ template "admission-controller.service.name" . }}
      path: "/couchbaseclusters/mutate"
    caBundle: {{ $tls.caCert }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "admission-controller.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "admission-controller.name" . }}
      annotations:
        checksum/config: {{ printf "%s%s" $tls.clientCert $tls.clientKey | sha256sum }}
    spec:
      imagePullSecrets:
  {{- range .Values.admissionController.imagePullSecrets }}
      - name: "{{ . }}"
  {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag }}"
        imagePullPolicy: {{ .Values.admissionController.imagePullPolicy }}
        command:
        - couchbase-operator-admission
        args:
          - "--zap-log-level"
          - {{if .Values.admissionController.verboseLogging }} "debug" {{else}} "info" {{end}}
          - "--tls-cert-file"
          - "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file"
          - "--tls-private-key-file"
          - "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file"
          {{- range $key, $value := .Values.admissionController.commandArgs }}
          - "--{{ $key }}={{ $value }}"
          {{- end }}
        ports:
        - name: https
          containerPort: {{ .Values.admissionService.port }}
        resources:
{{ toYaml .Values.admissionController.resources | indent 12 }}
    {{- with .Values.admissionController.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.admissionController.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumeMounts:
      - name: couchbase-operator-admission
        mountPath: "/var/run/secrets/couchbase.com/couchbase-operator-admission"
        readOnly: true
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: {{ template "admission-controller.secret.name" . }}
      securityContext:
        runAsNonRoot: {{ .Values.admissionController.runAsNonRoot }}
      serviceAccountName:  {{ template "admission-controller.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "admission-controller.service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
spec:
  selector:
    app.kubernetes.io/name : {{ template "admission-controller.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.admissionService.port }}
    targetPort: {{ .Values.admissionService.targetPort }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.admissionController.scope }}
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ printf "%sBinding" .Values.admissionController.scope }}
metadata:
  name: {{ template "admission-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-operator.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.admissionController.scope }}
  name: {{ template "admission-controller.fullname" . }}
{{- end }}
